### ISSUE TITLE
place is now lens

### ISSUE THREAD

**Issue by cdoorenweerd** [naturalis/openstack-docs#1]
sudo apt-get install unity-place-applications unity-place-files

should be:

sudo apt-get install unity-lens-applications unity-lens-files

**Comment by AtzeDeVries** [comment]
fixed, but xRDP does not work on Unity with Ubuntu 14.04. Can be fixed by using xfce as desktop. Will update tutorial later

**Comment by AtzeDeVries** [comment]
also fixed 14.04/xrdp issue
