### ISSUE TITLE
Instead of loggin in, ssh prompt's for password

### ISSUE THREAD

**Issue by manishlamichhane** [naturalis/openstack-docs#2]
![screenshot from 2016-11-06 23 46 57](https://cloud.githubusercontent.com/assets/4988114/20042520/8f8f93b8-a47b-11e6-9007-2b738cc9aa32.png)

Hi there! I followed all the steps you mentioned. But it prompts "enter password" instead of directly loggin in. What could be the reason? I cannot access the server and so I cannot check the logs in the server / OpenStack Instance.

**Comment by cdoorenweerd** [comment]
Hi,

try connecting with the username 'ubuntu' instead of 'root' ?

**Comment by AtzeDeVries** [comment]
using `ubuntu@<you-ip>` should solve the problem if the public key is injected correctly
